defaults:
  - polIter_r1d-1.5b_deepscaler_grpo
  - _self_

algorithm:
  adv_estimator: reinforce_plus_plus

  filter_groups:
    enable: true
    actual_train_batch_size: 128

data:
  train_batch_size: 300

actor_rollout_ref:
  actor:
    use_kl_loss: true
    kl_loss_type: mse
    kl_loss_coef: 0.00001
    clip_ratio_high: 0.28

    optim:
      weight_decay: 0.0
  
  rollout:
    calculate_log_probs: true
