- _target_: verl.tasks.math_like_task.MathLikeTaskConfig
  name: math_like_task
  loading_params:
    args:
      - zwhe99/DeepMath-103K
    kwargs:
      split: train
  problem_key: question
  answer_key: final_answer

  prompt_template: '{}\n\nPlease reason step by step, and put your final answer within \\boxed{{}}.'
  system_prompt: null

  data_source: "math_like_task:zwhe99/DeepMath-103K"